name: Deploy Infrastructure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      actions:
        description: 'Selecting actions for terraform'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
      environment:
        description: 'Selecting evironments for terraform'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - prod
jobs: 
  build:
    runs-on: ubuntu-latest
    name: DEPLOY INFRASTRUCTURE
    environment:  "terraform-${{ github.event.inputs.environment }}"
    steps:
#      - run: echo "$GITHUB_REF_NAME == ${{ github.ref_name }}"
#      - run: echo "$GITHUB_WORKSPACE == ${{ github.workspace }}"
#      - run: echo "${{ vars.KHANHTRUNG }} != $KHANHTRUNG"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets['AWS_ACCESS_KEY_ID'] }}
          aws-secret-access-key: ${{ secrets['AWS_SECRET_ACCESS_KEY'] }}
          aws-region: ap-southeast-1

      - name: Download credentials file from s3
        run: |
          cd aws-infra
          aws s3 cp s3://anycha-terraform-staging-test/terraform/terraform.tfstate .

      - name: Check file
        run: |
          ls $GITHUB_WORKSPACE/aws-infra
          sudo apt-get install -y tree
          tree $GITHUB_WORKSPACE/
          echo "Khanh trung dep trai"
