name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      actions :
        description: 'Selecting actions for terraform'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
#   push:
#     paths:
#       - 'aws-infra/**'
#       - '.github/workflows/infra-deploy.yml'

jobs: 
  build:
    runs-on: ubuntu-latest
    name: DEPLOY FRONTEND
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

    #   - name: Configure AWS Credentials
    #     uses: aws-actions/configure-aws-credentials@v2
    #     with:
    #       aws-access-key-id: ${{ secrets['AWS_ACCESS_KEY_ID'] }}
    #       aws-secret-access-key: ${{ secrets['AWS_SECRET_ACCESS_KEY'] }}
    #       aws-region: ap-northeast-1
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          terraform_wrapper: false

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan

      - name: Aplly Terraform
        run: terraform apply
        if: ${{ github.event.inputs.actions == 'apply' }} 